@echo off
REM Launch Claude Code (bypass permissions mode)
REM Generated by IDPF Framework installer
REM set DISABLE_AUTOUPDATER=1 && claude --permission-mode "bypassPermissions" "Start"
claude --permission-mode "bypassPermissions" "Start"
